# Generated by Django 6.0.5 on 2026-05-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_human_review_required_document_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='final_class',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('Finance', 'Finance'), ('IT', 'IT'), ('Legal', 'Legal'), ('Operations', 'Operations'), ('Procurement', 'Procurement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
