# Generated by Django 6.0.5 on 2026-05-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_review_notes_alter_document_final_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='human_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
