# Generated by Django 6.0.5 on 2026-08-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_human_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='confidence_margin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='second_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='second_confidence',
            field=models.FloatField(default=0),
        ),
    ]
