# Generated by Django 6.0.5 on 2026-08-11 13:25

from django.db import migrations, models


def populate_decision_routes(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    Document.objects.filter(confidence_score__lt=70.0).update(
        decision_route='human_review',
        decision_threshold=70.0,
    )
    Document.objects.filter(confidence_score__gte=70.0).update(
        decision_route='auto_approved',
        decision_threshold=70.0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_confidence_margin_document_second_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='decision_route',
            field=models.CharField(blank=True, choices=[('auto_approved', 'Auto-approved'), ('human_review', 'Human review required')], max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='decision_threshold',
            field=models.FloatField(default=70.0),
        ),
        migrations.RunPython(
            populate_decision_routes,
            migrations.RunPython.noop,
        ),
    ]
